apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: traefik

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-role
  namespace: traefik
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-rolebinding
  namespace: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-role
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: traefik
